### ISSUE TITLE
Add functionality to clone branch to gitea

### ISSUE THREAD

**Issue by marissaeinhorn** [uwardlaw/vater#145]
When working to resolve an issue with the code, process is to create a new branch.  In order to test the branch, you need to clone that branch to `gitea`

**Comment by marissaeinhorn** [comment]
`vater sync` error 

```
From rous:uwardlaw/rous
 * [new branch]      uwardlaw/task-vmInput -> origin/uwardlaw/task-vmInput
 tasks/createRange.applyEnclave.yml    | 16 ++++++++--------
 tasks/destroyRange.destroyEnclave.yml | 27 +++++++++++++++------------
 terraform/vsphere.auto.tfvars         |  2 +-
 terraform/windows-fundamentals.tf     | 11 ++++++++++-
 4 files changed, 34 insertions(+), 22 deletions(-)

Cloning into '/home/control/vater/control-services/data/gitea/git/rous'...
done.
error: refname refs/heads/main not found
fatal: Branch rename failed
Traceback (most recent call last):
  File "/home/control/vater/control-services/cli/vater.py", line 137, in <module>
    main()
  File "/home/control/vater/control-services/cli/vater.py", line 19, in main
    sync(c, p.args)
  File "/home/control/vater/control-services/cli/vater.py", line 44, in sync
    g.syncContentRepo()
  File "/home/control/vater/control-services/cli/gitea.py", line 88, in syncContentRepo
    self.__copyLatestContentRepo()
  File "/home/control/vater/control-services/cli/gitea.py", line 181, in __copyLatestContentRepo
    out += check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo', 'git', '--git-dir', '/home/control/vater/control-services/data/gitea/git/rous/.git/', 'branch', '-m', '-f', 'main', 'master']' returned non-zero exit status 128.
control@control-einhorn:~/rous/tasks$ cd ~/vater/control-services/cli/gitea.py
-bash: cd: /home/control/vater/control-services/cli/gitea.py: Not a directory

```

Need to add a variable for branch name in `vater sync` command and have gitea.py utilize that variable instead of `main`

**Comment by marissaeinhorn** [comment]
When running `vater sync` from `~/rous/terraform` the current branch syncs to gitea.  Running `vater sync` from `~/vater` does not and causes the errors above
