### ISSUE TITLE
`vater sync` errors on  __giteaExecAsGit function

### ISSUE THREAD

**Issue by marissaeinhorn** [uwardlaw/vater#165]
```
control@control-einhorn:~/vater/control-services$ vater sync -b iss82
Gitea Password:
Traceback (most recent call last):
  File "/home/control/vater/control-services/cli/vater.py", line 137, in <module>
    main()
  File "/home/control/vater/control-services/cli/vater.py", line 19, in main
    sync(c, p.args)
  File "/home/control/vater/control-services/cli/vater.py", line 43, in sync
    loginGitea(g)
  File "/home/control/vater/control-services/cli/vater.py", line 127, in loginGitea
    if(g.login(password=password)):
  File "/home/control/vater/control-services/cli/gitea.py", line 25, in login
    self.__createConfigUser(password=password)
  File "/home/control/vater/control-services/cli/gitea.py", line 114, in __createConfigUser
    self.__giteaExecAsGit(
  File "/home/control/vater/control-services/cli/gitea.py", line 236, in __giteaExecAsGit
    out = self.docker.dexec(
  File "/home/control/vater/control-services/cli/vDocker.py", line 67, in dexec
    out = subprocess.check_output(cmd, universal_newlines=True)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo', 'docker', 'exec', 'gitea', 'su', 'git', 'bash', '-c', '""gitea admin user create --admin --username config --email config@example.com --password cangetin --must-change-password=false""']' returned non-zero exit status 1.

```

**Comment by marissaeinhorn** [comment]
Ran `vater restart` to try and resolve the issue which errored 
```
vater restart
[sudo] password for control:
Stopping gitea    ... done
Stopping gitea_db ... done
Starting gitea_db ... done
Starting gitea    ... done
Gitea Password:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa8fc96b8b0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.100.5', port=3000): Max retries exceeded with url: /api/v1/users/config/tokens (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa8fc96b8b0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/control/vater/control-services/cli/vater.py", line 137, in <module>
    main()
  File "/home/control/vater/control-services/cli/vater.py", line 25, in main
    restart(c, p.args)
  File "/home/control/vater/control-services/cli/vater.py", line 77, in restart
    loginGitea(g)
  File "/home/control/vater/control-services/cli/vater.py", line 127, in loginGitea
    if(g.login(password=password)):
  File "/home/control/vater/control-services/cli/gitea.py", line 28, in login
    r = self.api.s.get(url=self.cfg['gitea']['api']['tokens'])
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='192.168.100.5', port=3000): Max retries exceeded with url: /api/v1/users/config/tokens (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa8fc96b8b0>: Failed to establish a new connection: [Errno 111] Connection refused'))
````

Resolved after `vater stop -s gitea` & `vater restart -s gitea`
