### ISSUE TITLE
Build a CI/CD pipeline that lives in Control and interfaces with Gitea

### ISSUE THREAD

**Issue by uwardlaw** [uwardlaw/vater#40]
The Gitea community recommends a combination of [Jenkins](https://github.com/jenkinsci/gitea-plugin) and [Drone](https://github.com/harness/drone) Gitea plugins.

- [x] #140
- [x] Setup Jenkins in Docker
  - [x] `Dockerfile`
  - [x] `Docker-compose.yml` 
- [x] Add Jenkins to CLI
  - [x] Restart
  - [x] Clean
  - [x] #152
  - [x] Setup
- [x] Begin development of unit testing (moved to 140)

**Comment by uwardlaw** [comment]
The pipeline build and execute seems pretty cut and dry based on the Drone [documentation](https://docs.drone.io/pipeline/docker/overview/). The devil's in the testing.

**Comment by uwardlaw** [comment]
We have a really rich environment with many tools, so we'll need an equal number of tools to support testing:
- [PyTest](https://docs.pytest.org/en/6.2.x/) for Python code (CLI)
- [Selenium](https://github.com/SeleniumHQ) for the Semaphore UI
- [Docker Hub](https://docs.docker.com/docker-hub/builds/automated-testing/) for testing images
- [ShellSpec](https://shellspec.info/) for shell code (setup.sh)
- [Terratest](https://terratest.gruntwork.io/docs/getting-started/quick-start/) for testing packer templates and terraform deployments
- [Jenkins](https://www.jenkins.io/doc/book/pipeline/) for CI/CD

**Comment by uwardlaw** [comment]
Associated with #42

**Comment by uwardlaw** [comment]
There's a great [tutorial](https://www.digitalocean.com/community/tutorials/how-to-automate-jenkins-setup-with-docker-and-jenkins-configuration-as-code) for automatic Jenkins installs. There are also [instructions](https://medium.com/@lfcgomes/testing-your-pull-requests-with-jenkins-b9a290431611) for running Jenkins testing automatically based on Github pull requests.

The idea is Github PR > Jenkins test > automatic acceptance / declination of PR

**Comment by uwardlaw** [comment]
`vater restart -s jenkins` deploys an errored Jenkins service:
```
io.jenkins.plugins.casc.ConfiguratorException: No configurator for the following root elements authorization
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:734)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:776)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:761)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:637)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:306)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:298)
Caused: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:180)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1153)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:222)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:121)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:291)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:49)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1186)
	at jenkins.model.Jenkins.<init>(Jenkins.java:978)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:269)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:286)
```

I suspect this due to `casc.yaml`:
```
authorization:
  globalMatrix:
    permissions:
    - '"Overall/Administer:admin"'
    - '"Overall/Read:authenticated"'
```

The error resolves when the single quotes around the items in `permissions` are removed.

`config.py` sets up the `authorization` block:
```
        cfg['jenkins']['casc']['authorization'] = {}
        cfg['jenkins']['casc']['authorization']['globalMatrix'] = {}
        cfg['jenkins']['casc']['authorization']['globalMatrix']['permissions'] = [
                "\"Overall/Administer:admin\"",
                "\"Overall/Read:authenticated\""
            ]
```

and `jenkins.py` creates the file:
```
        with open(self.cfg['jenkins']['casc_file_path'], 'w') as cascFile:
            yaml.dump(self.cfg['jenkins']['casc'], cascFile)
```

I opened a [question](https://stackoverflow.com/questions/70352698/how-can-i-add-double-quotes-to-items-in-a-python-yaml-dump-without-ruamel-yaml) for a more elegant solution with the `yaml` module. The `ruamel.yaml` option requires module installation which we want to avoid.

**Comment by uwardlaw** [comment]
The `authorization` block is actually value stored in `jenkins`... Regardless, that change still produces a configuration that errors:

```
java.lang.IllegalArgumentException: Permission can not be null for sid:admin"
	at hudson.security.GlobalMatrixAuthorizationStrategy.add(GlobalMatrixAuthorizationStrategy.java:95)
	at org.jenkinsci.plugins.matrixauth.integrations.casc.MatrixAuthorizationStrategyConfigurator.lambda$setPermissions$3(MatrixAuthorizationStrategyConfigurator.java:65)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.jenkinsci.plugins.matrixauth.integrations.casc.MatrixAuthorizationStrategyConfigurator.setPermissions(MatrixAuthorizationStrategyConfigurator.java:62)
	at io.jenkins.plugins.casc.Attribute.setValue(Attribute.java:231)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:356)
Caused: io.jenkins.plugins.casc.ConfiguratorException: string: Failed to set attribute permissions(class: class java.lang.String, multiple: true)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:358)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:275)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$doConfigure$16668e2$1(HeteroDescribableConfigurator.java:277)
	at io.vavr.CheckedFunction0.lambda$unchecked$52349c75$1(CheckedFunction0.java:247)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.doConfigure(HeteroDescribableConfigurator.java:277)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$configure$2(HeteroDescribableConfigurator.java:86)
	at io.vavr.control.Option.map(Option.java:392)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.lambda$configure$3(HeteroDescribableConfigurator.java:86)
	at io.vavr.Tuple2.apply(Tuple2.java:238)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.configure(HeteroDescribableConfigurator.java:83)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:92)
	at io.jenkins.plugins.casc.impl.configurators.HeteroDescribableConfigurator.check(HeteroDescribableConfigurator.java:55)
	at io.jenkins.plugins.casc.BaseConfigurator.configure(BaseConfigurator.java:350)
	at io.jenkins.plugins.casc.BaseConfigurator.check(BaseConfigurator.java:286)
	at io.jenkins.plugins.casc.ConfigurationAsCode.lambda$checkWith$8(ConfigurationAsCode.java:776)
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:712)
Caused: io.jenkins.plugins.casc.ConfiguratorException: jenkins: error configuring 'jenkins' with class io.jenkins.plugins.casc.core.JenkinsConfigurator configurator
	at io.jenkins.plugins.casc.ConfigurationAsCode.invokeWith(ConfigurationAsCode.java:718)
	at io.jenkins.plugins.casc.ConfigurationAsCode.checkWith(ConfigurationAsCode.java:776)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:761)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configureWith(ConfigurationAsCode.java:637)
	at io.jenkins.plugins.casc.ConfigurationAsCode.configure(ConfigurationAsCode.java:306)
	at io.jenkins.plugins.casc.ConfigurationAsCode.init(ConfigurationAsCode.java:298)
Caused: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
Caused: java.lang.Error
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:110)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:180)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:305)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1153)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:222)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:121)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused: org.jvnet.hudson.reactor.ReactorException
	at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:291)
	at jenkins.InitReactorRunner.run(InitReactorRunner.java:49)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1186)
	at jenkins.model.Jenkins.<init>(Jenkins.java:978)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at hudson.model.Hudson.<init>(Hudson.java:81)
	at hudson.WebAppMain$3.run(WebAppMain.java:269)
Caused: hudson.util.HudsonFailedToLoad
	at hudson.WebAppMain$3.run(WebAppMain.java:286)
```

**Comment by uwardlaw** [comment]
Removing the extra quotes solves the error.

The bootleg solution we didn't was to use a triple quoted string:

```
#
#        authBlock = \
#"""\
#authorizationStrategy:
#  globalMatrix:
#    permissions:
#    - "Overall/Administer:admin"
#    - "Overall/Read:authenticated"
#"""
#
#        with open(self.cfg['jenkins']['casc_file_path'], 'a') as cascFile:
#            cascFile.write(authBlock)
```

**Comment by uwardlaw** [comment]
Jenkins fails after adding persistent data storage with:

```
    volumes:
      - ./data/jenkins:/var/jenkins_home:rw
```

```
control@control:~/vater/control-services$ sudo docker-compose up jenkins
Starting jenkins ... done
Attaching to jenkins
jenkins         | Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
jenkins         | touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
jenkins exited with code 1
```
